CREATE TABLE IF NOT EXISTS T_COCHE (
    identificador INT PRIMARY KEY AUTO_INCREMENT,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    cilindrada INT NOT NULL,
    CONSTRAINT CHK_CILINDRADA_POSITIVA CHECK (cilindrada > 0)
);
